var lang_EN = {
    etiquet: {
        devolver_pro: 'Devolver Productos',
        no_registros: 'No records found.',
        option_ap: 'Appearance Options',
        cerrar_session: 'Log Out',
        pantalla_full: 'Maximize screen',
        atajo: 'Shortcut',
        proyectos: 'Projects',
        proyecto_recuentes: 'Recent projects',
        encabezado_fijo: 'Fixed Header',
        menu_fijo: 'Fixed Menu',
        navegacion_fijo: 'Fixed Navigation',
        footer_fijo: 'Fixed Footer',
        contenido_centrado: 'Centered content',
        menu_derecha: 'Menu on the <b>Right</b>',
        menu_arriba: 'Menu <b>Above</b>',
        para_daltonicos: 'For colorblind',
        estilos: 'Styles',
        defecto: 'Default',
        oscuro_elegante: 'Dark Elegant',
        ultra_claro: 'Ultra Claro',
        anaranjado: 'Orange',
        pixel: 'Pixel',
        trasparente: 'Transparent',
        celeste: 'Light blue',
        user: 'User',
        pass: 'Password',
        forgot_pass: 'I forgot my password?',
        copy_right: '&COPY; 2018 -  Perú. All rights reserved.',
        btn_entrar: 'Enter',
        search_menu: 'Search menu...',
        inactividad: 'Since you have been inactive, your session is about to expire.',
        tiempo_inactividad: 'Time remaining',
        continuar: 'Continue',
        salir: 'Go out',
        cierre_sesion: 'Closing session warning',
        loading: 'Loading...',
        new_menu: 'New Menu',
        edit_menu: 'Edit Menu',
        descripcion: 'Description',
        press_enter: 'Write and press [Enter]',
        t_alias: 'This alias will be used as a prefix for all the elements that will be contained in the menu that will be created, it must be unique in the system and it must end with two underscores (__). 10 characters maximum allowed.',
        t_ajax: `Event that is executed when clicking on the menu option. Ejm: Exe.load('MODULE','OPTION');`,
        alias: 'Alias',
        ajax: 'Ajax',
        activo: 'Active',
        inactivo: 'Inactive',
        btn_close: 'Close',
        btn_agregar: 'Add',
        btn_limpiar: 'Clean',
        icono: 'Icon',
        css: 'Css',
        new_boton: 'New Button',
        edit_boton: 'Edit Button',
        nombres: 'Nams',
        nombre: 'Name',
        theme: 'Design',
        estado: 'State',
        ant: 'Prev',
        sig: 'Next',
        fin: 'Finalize',
        tour: 'Tour',
        e_si: 'Yes',
        e_no: 'No',
        new_rol: 'New Rol',
        edit_rol: 'Edit Rol',
        rol_access: 'Accesses for: <span></span>',
        search_sensitive: 'Write to search...',
        rol: 'Rol',
        preview: 'Preview',
        new_categoria: 'New category',
        edit_categoria: 'Edit Category',
        visualizar: 'Visualize',
        imagen: 'Image',
        meta_titulo: 'Meta Title',
        meta_descripcion: 'Meta Description',
        meta_keywords: 'Meta Keywords',
        tagsinput_ph: 'Write and press enter.',
        caterorias: 'Categories',
        informacion_general: 'General information',
        configuracion: 'Configuration',
        productos: 'Products',
        documentos: 'Documents',
        principal: 'Main',
        modo_vista: 'View mode',
        categoria: 'Category',
        producto: 'Product',
        categoria_visible_para: 'Visible category for',
        visitante: 'Visitor',
        cliente: 'Client',
        registrar_producto: 'Register Product',
        tags: 'Tags',
        seo: 'SEO',
        caracterisricas: 'Features',
        valor: 'Value',
        seleccionar: 'Select',
        todos: 'Everyone',
        imagenes: 'Images',
        arrastra_aqui: 'Drag the files here or click to load them.',
        error_ulpoad: 'Error uploading the file',
        ingrese_valor_caracteristia: 'Enter the value of the characteristic.',
        seleccione_caracteristica: 'Select a feature.',
        registrar_vehiculo: 'Register Vehicle',
        duenio_vehiculo: 'Basic Data of the Owner',
        apellido_paterno: 'Last name',
        apellido_materno: `Mother's last name`,
        primer_nombre: 'First name',
        segundo_nombre: 'Second name',
        apellidos_nombres: 'Surnames and names',
        apellidos: 'Surnames',
        direccion: 'Address',
        panel: 'Panel',
        sistema_conversiones: 'Electronic Billing System',
        bienvenido: 'Welcome',
        tipo: 'Type',
        codigo_interno: 'Internal code',
        u_medida: 'U. Measure',
        precio_v: 'Price V.',
        new_bien_servicio: 'New product',
        edit_bien_servicio: 'Edit product',
        bien: 'Product',
        servicio: 'Service',
        precio_venta: 'Sale price',
        serie: 'Serie',
        tipo_comprobante: 'Type of Proof',
        numero_actual: 'Current number',
        new_serie: 'New serie',
        edit_serie: 'Edit Serie',
        local: 'Local',
        new_local: 'New Local',
        edit_local: 'Edit Local',
        codigo: 'Code',
        ubigeo: 'Ubigeo',
        email: 'Email',
        celular: 'Mobile',
        new_usuario: 'New user',
        edit_usuario: 'Edit User',
        usuario: 'User',
        administrador: 'Administrator',
        roles: 'Roles',
        note_email: 'This email will be the access user for the system.',
        series_asignadas: 'Assigned Series',
        asignadas_a: 'Select the series that will be assigned to:',
        tipo_doc: 'Type Doc.',
        num_doc: 'Nro. Doc.',
        razon_social: 'Business name',
        new_cliente: 'New client',
        edit_cliente: 'Edit client',
        nombre_comercial: 'Tradename',
        fijo: 'Fixed',
        direccion_fiscal: 'Fiscal address',
        direccion_1: 'Address 1',
        direccion_2: 'Address 2',
        email_princial: 'Main Email',
        email_1: 'Email 1',
        email_2: 'Email 2',
        _001: 'Sales Income',
        _002: 'Data of Comprobante',
        _003: 'Date of Em.',
        _004: 'Date of Venc.',
        _005: 'Type of currency',
        _006: 'Type of change',
        _007: 'Purchase order',
        _008: 'Generate referral guide?',
        _009: 'Gude Rem. Tran.',
        _010: 'Gude Rem. Sender',
        _011: 'Detail',
        _012: 'Product',
        _013: 'Quantity',
        _014: 'Type IGV',
        _015: 'Unit price',
        _016: 'Subtotal',
        _017: 'Total',
        _018: 'Observations',
        _019: 'Totals',
        _020: 'Exonerated',
        _021: 'Inafecta',
        _022: 'Taxed',
        _023: 'IGV',
        _024: 'Free',
        _026: 'No. Comp.',
        _027: 'No. Doc.',
        _028: 'Sent SUNAT',
        _029: 'Answer SUNAT',
        _030: 'ELECTRONIC BILL',
        _031: 'ELECTRONIC BOLETA',
        _032: 'Sending to SUNAT, please wait. Doc.: ',
        _033: 'Income Credit Note',
        _034: 'Reason',
        _035: 'Invoice price',
        _036: 'Document Affected',
        _037: 'RUC',
        _038: 'Date of issue',
        _039: 'Type Document Affected',
        _040: 'No. Doc. Affected',
        _041: 'Type Doc. Credit Note',
        _042: 'Serie Affec.',
        _043: 'No. Doc. Affec.',
        _044: 'ELECTRONIC CREDIT NOTE',
        _045: 'Debit Note Income',
        _046: 'Communication of Low',
        _047: 'Number',
        _048: 'Low date',
        _049: 'Low Communication Income',
        _050: 'ELECTRONIC DEBIT NOTE',
        _051: 'LOW COMMUNICATION',
        _052: 'Sending Outbound Communication to SUNAT, please wait. Doc.: ',
        _053: 'New supplier',
        _054: 'Edit supplier',
        _055: 'Minimum stock',
        _056: 'Current stock',
        _057: 'Add Products',
        _058: 'Purchase Price',
        _059: 'Gain %',
        _060: 'Only authorized personnel must modify the information. To modify type in the text boxes and press [Enter].',
        _061: 'Paid',
        _062: 'Credit',
        _063: 'Pay',
        _064: 'Search by identity document or names / company name',
        _065: 'Write to search',
        _067: 'Debt',
        _068: 'Residue',
        _069: 'Account',
        _070: 'Pending',
        _071: 'Cancelled',
        _072: 'Comprobante',
        _073: 'Date',
        _074: 'Amount',
        _075: 'Cancel',
        _076: 'Pagos de Doc. Num.:',
        _077: 'Fecha de Pago',
        _078: 'Fecha de Compra',
        _079: 'Forma de Pago',
        _080: 'Proveedor',
        _081: 'Ingreso de Compra',
        _082: 'Ventas por Local',
        _083: 'Desde',
        _084: 'Hasta',
        _085: 'Ver Detalle',
        _086: 'Detalle por Vendedor',
        _087: 'Detalle del Pedido',
        _088: 'Pedido N°',
        _089: 'Num. Pedido',
        _090: 'Stock Inicial',
        _091: 'Filtros de búsqueda',
        _092: 'Unidades',
        _093: 'Valorizado',
        _094: 'ID',
        _095: 'UM',
        _096: 'Inventario',
        _097: 'Entradas',
        _098: 'Salidas',
        _099: 'Valor Unitario',
        _100: 'Valor Total',
        _101: 'Aplica IGV',
        _102: 'Precio Ve. con IGV',
        _103: 'Detalle por Vendedor',
        _104: 'Ventas Brutas',
        _105: 'Ventas Netas',
        _106: 'Total IGV',
        _107: 'Utilidad',
        _108: 'Productos Vendidos',
        _109: 'Monto',
        _110: 'Ventas por Categoría',
        _111: 'Productos por Categoría según Local',
        _112: 'Stock',
        _113: 'Anulado',
        _114: 'Nueva Marca',
        _115: 'Editar Marca',
        _116: 'Marca',
        _117: 'Ventas Mensuales',
        _118: 'Total Ventas',
        _119: 'Por Pagar',
        _120: 'Por Cobrar',
        _121: 'Click para ir a Cuentas por Pagar',
        _122: 'Click para ir a Cuentas por Cobrar',
        _123: 'Ventas de Hoy',
        _124: 'Ventas de la Semana',
        _125: 'Ingrese el stock inicial para los productos que se agregarán al local',
        _126: 'Nueva Cotización',
        _127: 'Editar Cotización',
        _128: 'Cotización',
        _129: 'Enviar a Correo Electrónico',
        _130: 'New Cashbox',
        _131: 'Edit Cashbox',
        _132: 'Antes de iniciar las ventas debe <span id="sp_btnapc">[Aperturar]</span> caja.',
        _133: 'Cajas Asignadas',
        _134: 'Seleccione las cajas que seran asignadas al local:',
        _135: 'Aperturar Caja',
        _136: 'Seleccionae una Caja',
        _137: 'Detalle de Caja',
        _138: 'Cerrar Caja',
        _139: 'Caja',
        _140: 'Ventas',
        _141: 'Resumen',
        _142: 'Registro General',
        _143: 'Comprobantes Anulados',
        _144: 'Liquidación',
        _145: 'al',
        _146: 'Precio',
        _147: 'Perfil',
        _148: 'Empresa',
        _149: 'Datos de la Empresa',
        _150: 'Click para editar',
        _151: 'ELECTRONICA',
        _152: 'Son',
        _153: 'Cant.',
        _154: 'Desc.',
        _155: 'Hash',
        _156: 'Parámetros',
        _157: 'Parámetros',
        _158: 'Cuentas Bancarias',
        _159: 'Nueva Cuenta',
        _160: 'Editar Cuenta',
        _161: 'Banco',
        _162: 'Tipo Cuenta',
        _163: 'Configuraciones'
    },
    msn: {
        login_ok: 'Ingreso satisfactorio.',
        login_fail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Los datos se grabaron correctamente.',
        edit_ok: 'Los datos se actualizaron correctamente.',
        delete_ok: 'Registro se eliminó correctamente.',
        you_sure_delete: '¿Está seguro de eliminar el registro?',
        menu_exist: 'Descripción de menú ya existe.',
        alias_exist: 'Alias ya existe.',
        ajax_exist: 'Ajax ya existe.',
        boton_exist: 'Boton ya existe.',
        rol_exist: 'Rol ya existe.',
        copy_ok: 'Registro se duplico correctamente.',
        validate: 'Revise los campos marcados',
        propietario_exist: 'El propietario ya esta registrado en el sistema, no se puede volver a registrar.',
        upload_ok: 'Archivo se cargo correctamente.',
        aprobar: '¿Está seguro de aprobar el registro?',
        rechazar: '¿Está seguro de rechazar el registro?',
        operacion_ok: 'La operación se realizó correctamente.',
        ingrese_parametro: 'Ingrese un parametro de busqueda.',
        comuniquese: 'Sucedió un error inesperado, comuníquese con el Administrador del Sistema.',
        no_informacion: 'No tiene información',
        error_horario: 'El acceso al Sistema es de Lunes a Sabado de 7:00 AM a 7:00 PM.',
        antiguedad_10_anios: 'No se permiten vehículos con mas de 10 años de antiguedad. Verifique el año de fabricación.',
        video_grande: 'El video supera el límite máximo permitido de 132 MB',
        no_conforme2: 'No puede aprobar mientras la Conversión no este CONFORME en su totalidad.',
        no_tiene_registros: 'No tiene registros.',
        no_cargado: 'Documento aun no ha sido cargado.',
        categoria_exist: 'La categoría ya esta registrado en el sistema.',
        catalogo_exist: 'El producto ya esta registrado en el sistema.',
        _001: 'La serie debe iniciar con la letra F.',
        _002: 'La serie debe iniciar con la letra B.',
        _003: 'La serie debe iniciar con la letra B o F.',
        _004: 'La serie debe iniciar con la letra R.',
        _005: 'La serie debe iniciar con la letra P.',
        _006: 'La serie debe iniciar con la letra T.',
        serie_exist: 'La serie ya esta registrado en el sistema.',
        local_exist: 'El local ya esta registrado en el sistema.',
        codigo_exist: 'El código ya esta registrado en el sistema.',
        sel_rol: 'Seleccione al menos un ROL.',
        email_exist: 'El email ya esta registrado en el sistema.',
        sel_serie: 'Seleccione al menos una serie.',
        _007: '¿Esta seguro de quitar todas las series al usuario?',
        numero_doc_identidad_exist: 'Número de Documento de Identidad ya esta registrado.',
        _008: '¿Está seguro de generar el comprobante?',
        _009: 'Debe ingresar el número de guía de remitente.',
        _010: 'El número de guía de remitente debe ser un número válido.',
        _011: 'Revise los campos marcados en el detalle del documento.',
        _012: 'Ingrese el tipo de cambio.',
        _013: 'Correos se enviaron correctamente.',
        _014: '¿Esta seguro de enviar el documento a la SUNAT?',
        _015: 'El documento ya ha sido enviado a la SUNAT',
        _016: 'El documento aun no ha sido enviado a la SUNAT, no puede realizar esta acción.',
        _017: 'Seleccione una serie.',
        _018: 'Ingrese un número de documento.',
        _019: 'Documento no encontrado.',
        _020: 'Debe seleccionar los Productos afectados.',
        _021: 'El documento esta ANULADO.',
        _022: 'El documento tiene generada la nota de crédito: ',
        _023: 'El documento tiene generada la nota de débito: ',
        _024: 'El documento aun no ha sido enviado a la SUNAT.',
        _025: '¿Está seguro de dar de baja el documento?',
        _026: 'No puede anular el documento porque han pasado mas de 7 días desde su generación.',
        _027: 'Seleccione los productos a agregar.',
        _028: 'El documento no se puede anular, esta relacionada a una cuenta por cobrar.',
        pago_ok: ' El pago se relaizó correctamente.',
        _029: 'Aun no ha agregado los productos.',
        _030: '¿Está seguro de grabar la compra?',
        documento_registrado: '¿El documento de compra ya está registrado?',
        _031: 'Ingrese las fechas para la búsqueda.',
        esta_siendo_usado: 'No se puede eliminar. El registro está siendo usado en otras operaciones.',
        _032: 'Las Boletas no se pueden dar de baja, la SUNAT no lo permite. Consulte a su Contador.',
        marca_exist: 'La marca ya esta registrada en el sistema.',
        _033: '¿Está seguro de generar el pedido?',
        _034: 'Debe ingresar el stock inicial de los productos seleccionados.',
        _035: 'No tiene productos para agregar.',
        _036: 'Seleccione el tipo de documento.',
        _037: 'Ingrese un número de documento.',
        _038: 'El número de documento ingresado debe ser de 8 caracterres.',
        _039: 'El número de documento ingresado debe ser de 11 caracterres.',
        _040: 'tipo de documento no soportado',
        _041: 'Ingrese un número válido.',
        _042: 'Número de documento no encontrado.',
        _043: 'El cliente no tiene correo electrónico.',
        _044: 'El correo se envió correctamente.',
        _045: 'El correo no es válido.',
        caja_exist: 'Caja ya existe.',
        _046: 'Seleccione al menos una caja.',
        _047: 'Se quitarán todas las cajas. ¿Esta seguro de quitar las cajas?',
        open_caja_ok: 'Caja se aperturó corractamente.',
        _048: 'Para realizar las ventas, debe aperturar una caja.',
        close_caja_ok: 'Caja se cerró corractamente.',
        _049: 'No se ha configurado el formato de impresión, comuníquese con el administrador del sistema.',
        _050: 'Es necesario ingresar al ancho del TICKET.',
        cuenta_exist: 'La cuenta bancaria ya existe.'
    }
};