var lang_ES = {
    etiquet: {
        reset_stock: 'Devolver Stock a 0',
        modificacion_stock_detalle: 'Ajuste de Stock Detalle',
        stock_anterior: 'Stock Anterior',
        precio_unitario: 'Precio Unitario',
        personal: 'Personal',
        nuevo_ingreso: 'Nuevo Ingreso',
        nuevo_egreso: 'Nuevo Egreso',
        servicios: 'Servicios',
        remuneracion: 'Remuneración',
        devolver_pro: 'Devolver Productos',
        anular_pro: 'Anular Nota de venta',
        convertir_factura: 'Convertir a Factura',
        edit_nota_venta: 'Editar Nota de venta',
        pagar_cuenta: 'Pagar Cuenta',
        cobrar_cuenta: 'Cobrar Cuenta',
        edit_compra: 'Editar Compra',
        no_registros: 'No se encontraron registros.',
        option_ap: 'Opciones de Apariencia',
        cerrar_session: 'Cerrar sesión',
        pantalla_full: 'Maximizar pantalla',
        atajo: 'Atajo',
        proyectos: 'Proyectos',
        proyecto_recuentes: 'Proyectos recientes',
        encabezado_fijo: 'Encabezado Fijo',
        menu_fijo: 'Menú Fijo',
        navegacion_fijo: 'Navegación Fijo',
        footer_fijo: 'Footer Fijo',
        contenido_centrado: 'Contenido Centrado',
        menu_derecha: 'Menú a la <b>Derecha</b>',
        menu_arriba: 'Menú <b>Arriba</b>',
        para_daltonicos: 'Para daltónicos',
        estilos: 'Estilos',
        defecto: 'Defecto',
        oscuro_elegante: 'Oscuro Elegante',
        ultra_claro: 'Ultra Claro',
        anaranjado: 'Anaranjado',
        pixel: 'Pixel',
        trasparente: 'Trasparente',
        celeste: 'Celeste',
        user: 'Usuario',
        pass: 'Contraseña',
        forgot_pass: '¿Olvide mi contraseña?',
        copy_right: '&COPY; 2020 -  Perú. Todos los derechos reservados.',
        btn_entrar: 'Entrar',
        search_menu: 'Buscar menú...',
        inactividad: 'Como ha estado inactivo, su sesión está a punto de caducar.',
        tiempo_inactividad: 'Tiempo restante',
        continuar: 'Continuar',
        salir: 'Salir',
        cierre_sesion: 'Advertencia de cierre de sesión',
        loading: 'Cargando...',
        new_menu: 'Nuevo Menú',
        edit_menu: 'Editar Menú',
        descripcion: 'Descripción',
        press_enter: 'Escriba y presione [Enter]',
        t_alias: 'Este alias se utilizará como prefijo para todos los elementos que serán contenidos en el menú que se creará, debe ser único en el sistema y debe finalizar con dos guiones bajo(__). Se permiten 10 caracteres como máximo.',
        t_ajax: `Evento que se ejecutará al dar click en la opción de menú. Ejm: Exe.load('MODULO','OPCION');`,
        alias: 'Alias',
        ajax: 'Ajax',
        activo: 'Activo',
        inactivo: 'Inactivo',
        btn_close: 'Cerrar',
        btn_agregar: 'Agregar',
        btn_limpiar: 'Limpiar',
        icono: 'Icono',
        css: 'Css',
        new_boton: 'Nuevo Botón',
        edit_boton: 'Editar Botón',
        nombres: 'Nombres',
        nombre: 'Nombre',
        theme: 'Diseño',
        estado: 'Estado',
        ant: 'Ant',
        sig: 'Sig',
        fin: 'Finalizar',
        tour: 'Tour',
        e_si: 'Si',
        e_no: 'No',
        new_rol: 'Nuevo Rol',
        edit_rol: 'Editar Rol',
        rol_access: 'Accesos para: <span></span>',
        search_sensitive: 'Escriba para buscar...',
        rol: 'Rol',
        preview: 'Vista Previa',
        new_categoria: 'Nueva Categoría',
        edit_categoria: 'Editar Categoría',
        visualizar: 'Visualizar',
        imagen: 'Imagen',
        meta_titulo: 'Meta Título',
        meta_descripcion: 'Meta Descripción',
        meta_keywords: 'Meta Keywords',
        tagsinput_ph: 'Escribe y presiona enter.',
        caterorias: 'Categorías',
        informacion_general: 'Información General',
        configuracion: 'Configuración',
        productos: 'Productos',
        documentos: 'Documentos',
        principal: 'Principal',
        modo_vista: 'Modo vista',
        categoria: 'Categoría',
        producto: 'Producto',
        ubicacion: 'Ubicación',
        caja: 'X/Caja',
        p_publico: 'P. Pub',
        p_ferreteria: 'P. Fer',
        p_distribuidor: 'P. Dis',
        ultima_compra: 'Ultima Compra',
        categoria_visible_para: 'Categoría visible para',
        visitante: 'Visitante',
        cliente: 'Cliente',
        registrar_producto: 'Registrar Producto',
        tags: 'Tags',
        seo: 'SEO',
        caracterisricas: 'Características',
        valor: 'Valor',
        seleccionar: 'Seleccionar',
        todos: 'Todos',
        imagenes: 'Imagenes',
        arrastra_aqui: 'Arrastra los archivos aquí o haz click para cargarlos.',
        error_ulpoad: 'Error al subir el archivo',
        ingrese_valor_caracteristia: 'Ingrese el valor de la característica.',
        seleccione_caracteristica: 'Seleccione una característica.',
        registrar_vehiculo: 'Registrar Vehículo',
        duenio_vehiculo: 'Datos Básicos del Propietario',
        apellido_paterno: 'Apellido Paterno',
        apellido_materno: 'Apellido Materno',
        primer_nombre: 'Primer Nombre',
        segundo_nombre: 'Segundo Nombre',
        apellidos_nombres: 'Apellidos y Nombres',
        apellidos: 'Apellidos',
        direccion: 'Dirección',
        panel: 'Panel',
        sistema_conversiones: 'Software de Gestión Comercial',
        bienvenido: 'Bienvenido',
        tipo: 'Tipo',
        codigo_interno: 'Cod. Interno',
        codigo_barra: 'Cod. Barras',
        codigo_referencia: 'Cod. Referencia',
        u_medida: 'U. Medida',
        precio_v: 'Precio V.',
        new_bien_servicio: 'Nuevo Producto',
        edit_bien_servicio: 'Editar Producto',
        bien: 'Producto',
        servicio: 'Servicio',
        precio_venta: 'Precio venta',
        serie: 'Serie',
        tipo_comprobante: 'Tipo de Comprobante',
        numero_actual: 'Número Actual',
        new_serie: 'Nueva Serie',
        edit_serie: 'Editar Serie',
        local: 'Local',
        new_local: 'Nuevo Local',
        edit_local: 'Editar Local',
        codigo: 'Código',
        ubigeo: 'Ubigeo',
        email: 'Email',
        celular: 'Celular',
        new_usuario: 'Nuevo Usuario',
        edit_usuario: 'Editar Usuario',
        usuario: 'Usuario',
        administrador: 'Administrador',
        roles: 'Roles',
        note_email: 'Este email será el usuario de acceso para el sistema.',
        series_asignadas: 'Series Asignadas',
        asignadas_a: 'Seleccione las series que seran asignadas a:',
        tipo_doc: 'Tipo Doc.',
        num_doc: 'Nro. Doc.',
        razon_social: 'Razón Social',
        new_cliente: 'Nuevo Cliente',
        edit_cliente: 'Editar Cliente',
        nombre_comercial: 'Nombre Comercial',
        fijo: 'Fijo',
        direccion_fiscal: 'Dirección Fiscal',
        direccion_1: 'Dirección 1',
        direccion_2: 'Dirección 2',
        email_princial: 'Email Principal',
        email_1: 'Email 1',
        email_2: 'Email 2',
        _001: 'Emitir Comprobante',
        _002: 'Datos del Comprobante',
        _003: 'Fecha de Em.',
        _004: 'Fecha de Venc.',
        _005: 'Tipo de Moneda',
        _006: 'T. Cambio',
        _007: 'Orden de Compra',
        _008: '¿Generar guía de remisión?',
        _009: 'Guía Rem. Tran.',
        _010: 'Guía Rem. Remitente',
        _011: 'Detalle',
        _012: 'Producto',
        _013: 'Cantidad',
        _014: 'Tipo IGV',
        _015: 'P/UNIT',
        _016: 'Sub Total',
        _017: 'Total',
        _018: 'Observaciones',
        _019: 'Totales',
        _020: 'Exonerada',
        _021: 'Inafecta',
        _022: 'Gravada',
        _023: 'IGV',
        _024: 'Gratuita',
        _026: 'Num. Comp.',
        _027: 'Num. Doc.',
        _028: 'Enviado SUNAT',
        _029: 'Respuesta SUNAT',
        _030: 'FACTURA ELECTRONICA',
        _031: 'BOLETA ELECTRONICA',
        _032: 'Enviando a SUNAT, espere por favor. Doc.: ',
        _033: 'Ingreso de Nota de Crédito',
        _034: 'Motivo',
        _035: 'Precio Fact.',
        _036: 'Documento Afectado',
        _037: 'RUC',
        _038: 'Fecha de Emisión',
        _039: 'Tipo Documento Afectado',
        _040: 'Num. Doc. Afectado',
        _041: 'Tipo Doc. Nota de Crédito',
        _042: 'Serie Afec.',
        _043: 'Num. Doc. Afec.',
        _044: 'NOTA DE CREDITO ELECTRONICA',
        _045: 'Ingreso de Nota de Débito',
        _046: 'Comunicación de Baja',
        _047: 'Número',
        _048: 'Fecha Baja',
        _049: 'Ingreso de Comunicación de Baja',
        _050: 'NOTA DE DEBITO ELECTRONICA',
        _051: 'COMUNICACION DE BAJA',
        _052: 'Enviando Comunicación de baja a SUNAT, espere por favor. Doc.: ',
        _053: 'Nuevo Proveedor',
        _054: 'Editar Proveedor',
        _055: 'Stock Mínimo',
        _056: 'Stock Actual',
        _057: 'Agregar Productos',
        _058: 'Precio Compra',
        _059: 'Ganancia',
        _060: 'Solo personal autorizado debe modificar la información. Para modificar los <span style="font-weight:bolder">precios</span> escriba en las cajas de texto y presione [Enter].',
        _061: 'Pagado',
        _062: 'Crédito',
        _063: 'Pagar',
        _064: 'Buscar por documento de identidad o nombres / razón social',
        _065: 'Escriba para buscar',
        _067: 'Deuda',
        _068: 'Saldo',
        _069: 'Cuenta',
        _070: 'Pendiente',
        _071: 'Cancelado',
        _072: 'Comprobante',
        _073: 'Fecha',
        _074: 'Importe',
        _075: 'Cancelar',
        _076: 'Pagos de Doc. Num.:',
        _077: 'Fecha de Pago',
        _078: 'Fecha de Compra',
        _079: 'Forma de Pago',
        _080: 'Proveedor',
        _081: 'Ingreso de Compra',
        _082: 'Ventas por Local',
        _083: 'Desde',
        _084: 'Hasta',
        _085: 'Ver Detalle',
        _086: 'Detalle por Vendedor',
        _087: 'Detalle del Pedido',
        _088: 'Pedido N°',
        _089: 'Num. Pedido',
        _090: 'Stock Inicial',
        _091: 'Filtros de búsqueda',
        _092: 'Unidades',
        _093: 'Valorizado',
        _094: 'ID',
        _095: 'UM',
        _096: 'Inventario',
        _097: 'Entradas',
        _098: 'Salidas',
        _099: 'Valor Unitario',
        _100: 'Valor Total',
        _101: 'Aplica IGV',
        _102: 'Precio Ve. con IGV',
        _103: 'Detalle por Vendedor',
        _104: 'Ventas con IGV',
        _105: 'Ventas sin IGV',
        _106: 'Total IGV',
        _107: 'Utilidad',
        _108: 'Productos Vendidos',
        _109: 'Monto',
        _110: 'Ventas por Categoría',
        _111: 'Productos por Categoría según Local',
        _112: 'Stock',
        _113: 'Anulado',
        _114: 'Nueva Marca',
        _115: 'Editar Marca',
        _116: 'Marca',
        _117: 'Ventas Mensuales',
        _118: 'Total Ventas',
        _119: 'Por Pagar',
        _120: 'Por Cobrar',
        _121: 'Click para ir a Cuentas por Pagar',
        _122: 'Click para ir a Cuentas por Cobrar',
        _123: 'Ventas de Hoy',
        _124: 'Ventas de la Semana',
        _125: 'Ingrese el stock inicial para los productos que se agregarán al local',
        _126: 'Nueva Cotización',
        _127: 'Editar Cotización',
        _128: 'Cotización',
        _129: 'Enviar a Correo Electrónico',
        _130: 'Nueva Caja',
        _131: 'Editar Caja',
        _132: 'Antes de iniciar las ventas debe <span id="sp_btnapc">[Aperturar]</span> caja.',
        _133: 'Cajas Asignadas',
        _134: 'Seleccione las cajas que seran asignadas a:',
        _135: 'Aperturar Caja',
        _136: 'Seleccione una Caja',
        _137: 'Detalle de Caja',
        _138: 'Cerrar Caja',
        _139: 'Caja',
        _140: 'Ventas',
        _141: 'Resumen',
        _142: 'Registro General',
        _143: 'Comprobantes Anulados',
        _144: 'Liquidación',
        _145: 'al',
        _146: 'Precio',
        _147: 'Perfil',
        _148: 'Empresa',
        _149: 'Datos de la Empresa',
        _150: 'Click para editar',
        _151: 'ELECTRONICA',
        _152: 'Son',
        _153: 'Cant.',
        _154: 'Desc.',
        _155: 'Hash',
        _156: 'Parámetros',
        _157: 'Parámetros',
        _158: 'Cuentas Bancarias',
        _159: 'Nueva Cuenta',
        _160: 'Editar Cuenta',
        _161: 'Banco',
        _162: 'Tipo Cuenta',
        _163: 'Configuraciones',
        _164: 'Guía de Remisión',
        _165: 'Datos de la Guía',
        _166: 'Motivo de Traslado',
        _167: 'Destinatario',
        _168: 'Envio',
        _169: 'Transporte',
        _170: 'Nuevo',
        _171: 'Editar',
        _172: 'Registre todos los vehículos que pertenecen a: ',
        _173: 'Nuevo Vehículo',
        _174: 'Editar Vehículo',
        _175: 'Vehículo',
        _176: 'Conductor',
        _177: 'Placa',
        _178: 'Punto de partida',
        _179: 'Punto de llegada',
        _180: 'Fecha de inicio de traslado',
        _181: 'Público',
        _182: 'Privado',
        _183: 'Modalidad de transporte',
        _184: 'Número de bultos',
        _185: 'VENTA',
        _186: 'Item',
        _187: '¿Enviar a SUNAT?',
        _188: 'Sí, enviar ahora',
        _189: 'No, enviar despues',
        _190: 'GUIA DE REMISION ELECTRONICA',
        _191: 'La guía de remisión ya se envió a SUNAT.',
        _192: 'Tipo Doc. Nota de Débito',
        _193: 'Para registrar las series, diríjase a: <b>Maestros -> Series</b>',
        _194: 'Aquí se registrará todo los productos para luego ser distribuidos a las <b>tiendas/almacenes/sucursales</b> para sus <b>ventas posteriores.</b>',
        _195: 'Registre todas las series de los comprobantes que necesitará para las ventas de sus productos. Luego debe asignar las series a las personas que realizarán las ventas, este proceso lo debe realizar en: <b>Configuración -> Seguridad -> Usuarios.',
        _196: 'El email principal es necesario para enviar los comprobantes de venta al cliente.',
        _197: 'Ganancia por Producto',
        _198: 'Aplique el % de ganacia a todos los productos del local: ',
        _199: 'Concepto',
        _200: 'Vuelto',
        _201: 'Dinero recibido',
        _202: 'Vuelto',
        _203: 'T. moneda',
        _204: 'Modificar Comprobante',
        _205: 'Cambiar Contraseña',
        _206: 'Ingrese la nueva contraseña para:',
        _207: 'Nueva contraseña',
        _208: 'Formato de impresion para documentos de venta (PDF, TICKET)',
        _209: '¿Cómo se aplicará la ganacia en el precio de venta de los productos?',
        _210: 'Porcentaje',
        _211: 'Ingresos',
        _212: 'Egresos',
        _213: 'Efectivo',
        _214: 'Vuelto',
        _215: 'Nuevo Movimiento',
        _216: 'Origen',
        _217: 'Destino',
        _218: 'Ajuste de Stock',
        _219: 'Solo se visualizará los productos que tienen stock.',
        _220: 'Items',
        _221: '+',
        _222: '-',
        _235: 'Ingresos',
        _236: 'Egresos',
        _240: 'Reporte General de Ventas',
        _241: 'Totales Efectivo',
        _242: 'Totales Credito',
        _243: 'Condicion',
        _244: 'Caja Chica',
        _245: 'Operacion',
        _246: 'Excel',
        _256: 'Proveedores',
        _257: 'Marcas',
        _258: 'Clientes',
        _259: 'Ventas del Día',
        _260: 'Compras del Mes',
        _261: 'Productos Más Vendidos',
        _262: 'Nro.',  
        _263: 'VENDER',
        _264: 'Vendedor',
        _265: 'BIENVENIDO AL TOMA DE PEDIDOS',
        _266: 'DETALLES DEL PEDIDO',
        _267: 'Venta y Utilidad Total de Tienda Principal',
        _268: 'Venta Total',
        _269: 'Utilidad Total',
        _270: 'Vendedores Más Productivos',
        _271: 'Vendedor',
        _272: 'Total S/.',
        _273: 'Descripción Del Producto',
        _274: 'Productos Vendidos',
        _275: 'Ventas y Utilidad Total de Tienda Principal',
        _276: 'CAJA(S)',
        _277: 'VENTAS',
        _278: 'TOTALES EFECTIVO',
        _279: 'TOTALES CREDITO',
        _280: 'POR COBRAR',
        _281: 'POR PAGAR',
        _282: 'RESUMEN',
        _283: '',
        _284: 'PEDIDOS',
        _285: 'Productos con stock 0',
        _286: 'Productos con stock menor a 5',
        _287: 'Ganancia Publico(%)',
        _288: 'Ganancia Ferreteria(%)',
        _289: 'Ganancia Distribuidor(%)',
        _290: 'Precio de venta Publico(S./)',
        _291: 'Precio de venta Ferreteria(S./)',
        _292: 'Precio de venta Distribuidor(S./)',
        _293: 'Reporte general de productos',
        _294: 'Reporte de utilidad por producto',
        total_soles: 'Total en soles'
    },
    msn: {
        login_ok: 'Ingreso satisfactorio.',
        login_fail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Los datos se grabaron correctamente.',
        edit_ok: 'Los datos se actualizaron correctamente.',
        delete_ok: 'Registro se eliminó correctamente.',
        you_sure_delete: '¿Está seguro de eliminar el registro?',
        menu_exist: 'Descripción de menú ya existe.',
        alias_exist: 'Alias ya existe.',
        ajax_exist: 'Ajax ya existe.',
        boton_exist: 'Boton ya existe.',
        rol_exist: 'Rol ya existe.',
        copy_ok: 'Registro se duplico correctamente.',
        validate: 'Revise los campos marcados',
        propietario_exist: 'El propietario ya esta registrado en el sistema, no se puede volver a registrar.',
        upload_ok: 'Archivo se cargo correctamente.',
        aprobar: '¿Está seguro de aprobar el registro?',
        rechazar: '¿Está seguro de rechazar el registro?',
        operacion_ok: 'La operación se realizó correctamente.',
        ingrese_parametro: 'Ingrese un parametro de busqueda.',
        comuniquese: 'Sucedió un error inesperado, comuníquese con el Administrador del Sistema.',
        no_informacion: 'No tiene información',
        error_horario: 'El acceso al Sistema es de Lunes a Sabado de 7:00 AM a 7:00 PM.',
        antiguedad_10_anios: 'No se permiten vehículos con mas de 10 años de antiguedad. Verifique el año de fabricación.',
        video_grande: 'El video supera el límite máximo permitido de 132 MB',
        no_conforme2: 'No puede aprobar mientras la Conversión no este CONFORME en su totalidad.',
        no_tiene_registros: 'No tiene registros.',
        no_cargado: 'Documento aun no ha sido cargado.',
        categoria_exist: 'La categoría ya esta registrado en el sistema.',
        catalogo_exist: 'El producto ya esta registrado en el sistema.',
        _001: 'La serie debe iniciar con la letra F.',
        _002: 'La serie debe iniciar con la letra B.',
        _003: 'La serie debe iniciar con la letra B o F.',
        _004: 'La serie debe iniciar con la letra R.',
        _005: 'La serie debe iniciar con la letra P.',
        _006: 'La serie debe iniciar con la letra T.',
        serie_exist: 'La serie ya esta registrado en el sistema.',
        local_exist: 'El local ya esta registrado en el sistema.',
        codigo_exist: 'El código ya esta registrado en el sistema.',
        sel_rol: 'Seleccione al menos un ROL.',
        email_exist: 'El email ya esta registrado en el sistema.',
        sel_serie: 'Seleccione al menos una serie.',
        _007: '¿Esta seguro de quitar todas las series al usuario?',
        numero_doc_identidad_exist: 'Número de Documento de Identidad ya esta registrado.',
        _008: '¿Está seguro de generar el comprobante?',
        _009: 'Debe ingresar el número de guía de remitente.',
        _010: 'El número de guía de remitente debe ser un número válido.',
        _011: 'Revise los campos marcados en el detalle del documento.',
        _012: 'Ingrese el tipo de cambio.',
        _013: 'Correos se enviaron correctamente.',
        _014: '¿Esta seguro de enviar el documento a SUNAT?',
        _015: 'El documento ya ha sido enviado a SUNAT',
        _016: 'El documento aun no ha sido enviado a SUNAT, no puede realizar esta acción.',
        _017: 'Seleccione una serie.',
        _018: 'Ingrese un número de documento.',
        _019: 'Documento no encontrado.',
        _020: 'Debe seleccionar los Productos afectados.',
        _021: 'El documento esta ANULADO.',
        _022: 'El documento tiene generada la nota de crédito: ',
        _023: 'El documento tiene generada la nota de débito: ',
        _024: 'El documento aun no ha sido enviado a SUNAT.',
        _025: '¿Está seguro de dar de baja el documento?',
        _026: 'No puede anular el documento porque han pasado mas de 7 días desde su generación.',
        _027: 'Seleccione los productos a agregar.',
        _028: 'El documento no se puede anular, esta relacionada a una cuenta por cobrar.',
        pago_ok: ' El pago se relaizó correctamente.',
        _029: 'Aun no ha agregado los productos.',
        _030: '¿Está seguro de grabar la compra?',
        documento_registrado: '¿El documento de compra ya está registrado?',
        _031: 'Ingrese las fechas para la búsqueda.',
        esta_siendo_usado: 'No se puede eliminar. El registro está siendo usado en otras operaciones.',
        _032: 'Las Boletas no se pueden dar de baja, SUNAT no lo permite. Consulte a su Contador.',
        marca_exist: 'La marca ya esta registrada en el sistema.',
        _033: '¿Está seguro de generar el pedido?',
        _034: 'Debe ingresar el stock inicial de los productos seleccionados.',
        _035: 'No tiene productos para agregar.',
        _036: 'Seleccione el tipo de documento.',
        _037: 'Ingrese un número de documento.',
        _038: 'El número de documento ingresado debe ser de 8 caracterres.',
        _039: 'El número de documento ingresado debe ser de 11 caracterres.',
        _040: 'tipo de documento no soportado',
        _041: 'Ingrese un número válido.',
        _042: 'Número de documento no encontrado.',
        _043: 'El cliente no tiene correo electrónico.',
        _044: 'El correo se envió correctamente.',
        _045: 'El correo no es válido.',
        caja_exist: 'Caja ya existe.',
        _046: 'Seleccione al menos una caja.',
        _047: 'Se quitarán todas las cajas. ¿Esta seguro de quitar las cajas?',
        open_caja_ok: 'Caja se aperturó corractamente.',
        _048: 'Para realizar las ventas, debe aperturar una caja.',
        close_caja_ok: 'Caja se cerró corractamente.',
        _049: 'No se ha configurado el formato de impresión, comuníquese con el administrador del sistema.',
        _050: 'Es necesario ingresar al ancho del TICKET.',
        cuenta_exist: 'La cuenta bancaria ya existe.',
        documento_exist: 'El número de documento ya existe.',
        placa_exist: 'Placa de vehículo ya existe.',
        _051: '¿Está seguro de generar la guía de resmisión?',
        _052: 'El precio a cotizar no debe ser menor que el precio costo, operación no permitida.',
        _053: 'Aún no se ha aperturado CAJA, diríjase a: Ventas -> Emisión de Comprobantes -> BOTON NUEVO -> BOTON APERTURAR',
        _054: ' Ya quedan menos de 6',
        _055: 'El tipo de cambio debe ser numérico.',
        _056: 'Las Notas de Venta no se envían a SUNAT.',
        sale_no_last: 'El documento no se puede eliminar porque ya se genero el siguiente correlativo.',
        _057: 'El documento ya ha sido enviado a SUNAT, no se puede realizar esta operación.',
        _058: 'El documento no se puede eliminar porque ya se proceso el cierre de caja.',
        _059: 'El documento no se puede modificar porque ya se proceso el cierre de caja.',
        _060: 'El usuario se creo correctamente. Se ha enviado los accesos al correo brindado, si no logra visualizar el correo en su bandeja, revise los SPAM o CORREOS NO DESEADOS.',
        _061: 'Ingrese la información.',
        change_pass_ok: 'La contraseña se modificó correctamente. Se ha enviado los accesos al correo del usuario, si no logra visualizar el correo en su bandeja, revise los SPAM o CORREOS NO DESEADOS.',
        _062: 'Ingrese la fecha.',
        _063: 'Ingrese el importe.',
        _064: 'Ingrese el concepto.',
        _065: '¿Está seguro de guardar la información?',
        _066: 'Seleccione el local de origen.',
        _067: 'La cantidad a trasladar es mayor que el stock actual.',
        _068: 'no cuenta con stock para la venta.',
        _069: 'Seleccione una cantidad de productos valida.'
    }
};