var tour_ES = {
    grid: {
        c_sort: 'Las columnas que tengan las flechas de ordenamiento, pueden ser ordenadas dando click.',
        c_more_filters: 'Presione este botón para obtener mas opciones de búsqueda.',
        c_chose_1: 'Seleccione el tipo de búsqueda para el primer texto.',
        c_chose_2: 'Seleccione el tipo de búsqueda para el segundo texto.',
        c_and_or: 'Seleccione como desea realizar la búsqueda con ambos textos.<br>AND -> La búsqueda toma en cuenta ambos textos.<br>OR -> La búsqueda toma en cuenta uno de los dos textos.',
        c_txt_filter_2: 'Escrbiba el segundo texto a buscar.',
        c_btn_filter: 'Click en "Filtrar" para realizar la búsqueda.',
        c_clear_search: 'Click en "Limpiar" para restaurar la información del data grid',
        c_btn_group: 'Click en este botón para mostrar la lista de acciones que puede realizar por cada registro.',
        c_lst_length: 'Seleccione la cantidad de registros que desea ver por pagina.',
        c_btn_refresh: 'Click en este botón para refrescar el data grid.',
        c_pagin: 'En esta sección puede navegar por las diferentes páginas del data grid.',
        c_ax_edit: 'Click en "Editar" para mostrar el formulario con los datos del registro y poder modificarlos.',
        c_ax_delete: 'Click en "Eliminar" para que el registro sea borrado.'
    },
    app: {
        t_msn_app: 'Mensajes del Sistema',
        c_msn_app_cont: 'Este botón le permite visualizar los diferentes mensajes del sistema.',
        t_idioma: 'Idioma',
        c_idioma: 'En esta sección puede seleccionar el idioma del sistema.',
        t_rol: 'Rol',
        c_rol: 'Aquí podrá seleccionar el ROL con el que interactuará con el sistema. Cada ROL tiene diferentes niveles de accceso.',
        t_full_sreen: 'Pantalla Completa',
        c_full_sreen: 'Presione este botón para maximizar la pantalla y obtener una mejor experiencia con el sistema.',
        t_short_menu: 'Atajo de menú',
        c_short_menu: 'Aquí escriba la opción del sistema al cual desea ingresar.',
        t_out: 'Salir',
        c_out: 'Presione este botón para salir del sistema.',
        t_dynamic_option: 'Opciones dinámicas',
        c_dynamic_option: 'Oculte las opciones de manera dinámica y obtenga mas espacio para interacatuar con el sistema.',
        t_template: 'Template',
        c_template: 'Personalice el diseño del sistema como mas le guste.',
        t_options: 'Opciones',
        c_options: 'En esta sección puede navegar por las opciones del sistema.',
        t_access: 'Acceso Directo',
        c_access: 'Al presionar su nombre, el sistema le mostrará los accesos directos.',
        c_access_direct: 'Acceso directo a los módulos.',
        c_tab: 'Cuando de trabaja con varias pestañas, dar click en el nombre para mostrar el área de trabajo.',
        c_close_tab: 'Click en "x" para cerrar la pestaña.'
    },
    boton: {
        t_boton: 'Nuevo Botón',
        c_boton: 'Click en "Nuevo" para mostrar el formulario donde podrá registrar un nuevo botón para el sistema.',
        t_excel: 'Exportar a Excel',
        c_excel: 'Click en "Excel" para exportar a un archivo excel el listado de todos los botones que están configurados en el sistema.',
        c_filter_name: 'Escriba y presione Enter para realizar una búsqueda por nombres.',
        c_filter_alias: 'Escriba y presione Enter para realizar una búsqueda por alias.',
        c_filter_estado: 'Seleccione un estado para realizar la búsqueda.',
        c_descripcion: 'Ingrese un nombre para el botón (debe tener como prefijo el idioma y un guión: EN-, ES-; y presionar [Enter] para seguir agregando los nombres segun los idiomas que se necesite), que haga referencia al proceso o acción que realizará en el sistema, como mínimo 3 carateres.',
        c_alias: 'El alias debe ser único, y se usará como ID del botón en el sistema, se permite como máximo 10 caracteres y como mínimo 3 carateres.',
        c_icono: 'Css para el icono del botón. Use los iconos de Font Awesome v 4.7, como mínimo 3 carateres.',
        c_css: 'Css para el diseño del botón, como mínimo 3 carateres.'
    },
    rol: {
        c_rol: 'Click en "Nuevo" para mostrar el formulario donde podrá registrar un nuevo rol para el sistema.',
        c_excel: 'Click en "Excel" para exportar a un archivo excel el listado de todos los roles del sistema.',
        c_ax_preview: 'Click en "Vista Previa" para visualizar los perimisos asignados al rol.',
        c_ax_access: 'Click en "Accessos" para mostrar el formulario donde podrá agregar o quitar los permisos al rol.',
        c_ax_copy: 'Click en "Duplicar" para realizar una copia del rol y todos sus permisos.',
        c_descripcion: 'Debe ingresar el nombre del rol, con el prefijo del idioma (ES-, EN-), presione [Enter] para seguir agregando los nombres segun los idiomas que se necesite.',
        c_view_access: 'Click para desplegar y visualizar los permisos asignados.',
        c_access: 'Click para desplegar y visualizar las opciones.',
        c_permiso: 'Click en checkbox para asignar o quitar permiso, una vez asignado el permiso se activará el botón "Configurar".',
        c_ver_botones: 'Click en "Configurar" para agregar o quitar los botones con que contará el permiso asignado.',
        c_search_boton: 'Aquí puede escribir el nombre del botón para realizar una busqueda rápida.',
        c_no_asignado: 'En esta sección se visualizarán los botones que aun no se han asignado.',
        c_si_asignado: 'En esta sección se visualizarán los botones que ya se han asignado.',
        c_add_element: 'Seleccione el botón y arrastrelo hacia el área verde y sueltelo para asignarlo.',
        c_remove_element: 'Seleccione el botón y arrastrelo hacia el área roja y sueltelo para quitarlo.'
    },
    _0001: 'Si tiene un número de pedido, escríbalo y presione enter para cargar los productos en el detalle del documento.',
    _0002: 'En este componente se muestra los tipos de documentos asignados a un usuario. Si aun no se han asignado documentos al usuario, diríjase a: Configuración -> Seguridad -> Usuarios. (Es obligatorio)',
    _0003: 'En este componente se muestra las series relacionadas al tipo de documento. Si aun no ha generado las series, diríjase a: Facturación -> Maestros -> Series. (Es obligatorio)',
    _0004: 'Número correlativo del documento que se genera automaticamente. (Es obligatorio)',
    _0005: 'Algunos documentos tienen fecha de vencimiento, aqui debe ser ingresada. (Es opcional)',
    _0006: 'Tipo de moneda en el cual se realiza la venta.',
    _0007: 'En este componente se muestra los clientes que se han registrado en el sistema, si es un cliente nuevo, debe registrarlo pulsando el boton Agregar Cliente. (Es obligatorio)',
    _0008: 'Presione este botón para poder registrar un nuevo cliente.',
    _0009: 'En este componente se muestra las formas de pago en que se puede realizar una venta.',
    _0010: 'Si la venta está relacionada a una orden de compra, puede ingresar el número en este campo. (Es opcional)',
    _0011: 'Cuando la venta se realiza en una moneda extranjera, es obligatorio ingresar el tipo de cambio.',
    _0012: 'En este componente se muestra las direcciones del cliente. Para agregar una dirección al cliente, diríjase a: Facturación -> Maestros -> Terceros -> Clientes. (Es opcional)',
    _0013: 'Si la venta está relacionada a una guía de remisión del remitente, deberá ingresar el número en este campo. <br/>(Es opcional)',
    _0014: 'La venta puede ser a crédito o pagado, en esta sección debe indicar el estado de la venta.',
    _0015: 'Presione este botón para agregar items al detalle de la venta.',
    _0016: 'Si la venta está relacionada a una guía de remisión de transportista, deberá ingresar el número en este campo. <br/>(Es opcional)',
    _0017: 'Escriba el nombre del producto para realizar una búsqueda, luego seleccione el producto deseado. (Es obligatorio)',
    _0018: 'Aqui debe ingresar la cantidad de productos a vender. (Es obligatorio)',
    _0019: 'En este componente se muetra el listado de Tipo de Afectación de IGV según SUNAT, se debe indicar que tipo de afectación se aplica al producto. Por lo general es: Gravado - Operación Onerosa.',
    _0020: 'El precio de venta del prodcucto incluído el igv. Este campo puede ser modificado en caso sea necesario (Es obligatorio)',
    _0021: 'Este monto es la multiplicación de la cantidad por el precio unitario, no incluye igv.',
    _0022: 'Este monto es la multiplicación de la cantidad por el precio unitario, si incluye igv.',
    _0023: 'Presione este botón para eliminar el producto de la venta',
    _0024: 'Puede agregar una observación a la venta. (Es opcional)',
    _0025: 'Al presionar este botón se generara el comprobante de venta, luego desde el listado de documentos de venta podrá enviarlo a la SUNAT.'
};

