<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
    <head>
        <title>3VFACT</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div style="background: #81BEF7;width: 80%;position: relative;margin: auto;padding: 0 20px 0 20px">
            <table style="width: 70%;background: #fff" align="center">
                <tr>
                <td>
                    <img src="{LOGO}">
                </td>
                <td><b>Documento Electrónico</b></td>
                </tr>
                <tr>
                <td colspan="2">
                    <p>
                        Se le adjunta los documentos de su comprobante electrónico N° {NUMDOC}.
                    </p>
                    <p>Estamos a su servicio.</p>
                </td>
                </tr>
            </table>
        </div>
        <hr>
    </body>
</html>
