<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL ?>public/css/login.css">

<div class="split-login">
    <div class="split-login-half split-login-left">
        <div class="split-login-form">
                <div class="login-form">
                    <h1 class="titulo">Login</h1>
                    <form class="" id="LG__formLogin" name="LG__formLogin">
                    <div class="form-group">
                        <label for="">Usuario</label>
                        <input type="text" class="form-control tr-language-ph" data-trph="user" id="LG__txtUser" name="LG__txtUser">
                    </div>
                    <div class="form-group">
                        <label for="">Password</label>
                        <input type="password" class="form-control tr-language-ph" data-trph="pass" id="LG__txtClave" name="LG__txtClave">
                    </div>
                    <a class="small-text tr-language hide" href="javascript:;" data-tr="forgot_pass"></a>
                    <button id="btn_entrar" type="submit" class="btn btn-primary btn-block"><i class="fa fa-unlock"></i> <span class="tr-language" data-tr="btn_entrar"></span></button>

                    </form>
                </div>
                
        </div>
        <div class="split-login-footer">
        © 2021 SisfactePro | todo los derechos reservados
        </div>
    </div>
    <div class="split-login-half split-login-right"></div>
</div>

